### ISSUE TITLE
Idea for Markdown explanations of each solution

### ISSUE THREAD

**Issue by cycle4passion** [total-typescript/beginners-typescript#17]
What about adding a corresponding markdown file for each lesson. This would essentially be what you would be saying if you were teaching it as you did on livestream.

# 01-number.problem.md

We need to tell Typescript what type of data are expect for parameters a and b in the addTwoNumbers function. The format to declare the type of a function parameter is to add _`: type`_ following each parameter. In this case it would be `: number`. With this information, Typescript can go to work enforcing appropriate typing of the addTwoNumbers function parameters.

Even better, format the makdown file so that the top describes the problem/expectations and then a link scrolls down to describe the answer.

**Comment by mattpocock** [comment]
In the full video course, I'll be adding video explanations for each problem/solution. This repository represents my sketches for workshop/course material, so I won't be adding written explanations here.
