### ISSUE TITLE
Exercise 08 can be solved without a `User` return type annotation

### ISSUE THREAD

**Issue by with-heart** [total-typescript/beginners-typescript#4]
Providing a default user that matches the shape of `User` without actually providing a return type annotation passes the tests and typecheck, but that obviously avoids the intended lesson.

```ts
const makeUser = () => {
  return {
    id: 1,
    firstName: '',
    lastName: '',
    role: 'user',
    posts: [
      {
        id: 1,
        title: '',
      },
    ],
  }
}
```

**Comment by mattpocock** [comment]
You'll notice that that _is_ actually one of the valid solutions (solution 2)! My point here (which is hard to grok without accompanying videos) is that you don't _need_ to annotate the return type of functions.
