### ISSUE TITLE
Exercise 07 provides no explanation of the problem

### ISSUE THREAD

**Issue by with-heart** [total-typescript/beginners-typescript#5]
Possibly related to #3 (wrong explanation included?)

I think this exercise might warrant a comment above/within `User` that points out that *some change* should be made to `User` in order to resolve the type error, similar to the comment in 06 noting that changing the `role` property is the way to solve the problem.

**Comment by mattpocock** [comment]
The course so far is basically just the raw exercises. In the future, each exercise will come with an accompanying problem/solution video which explains things.

So I'll defer the 'explanation' stuff until then.

**Comment by mattpocock** [comment]
Also, thanks so much for taking a look at the content @with-heart & others, y'all are the best.

**Comment by with-heart** [comment]
@mattpocock Thank YOU for building something so awesome!
