### ISSUE TITLE
Exercise 09 doesn't have a description nor instructions

### ISSUE THREAD

**Issue by guilhermedeandrade** [total-typescript/beginners-typescript#7]
First of all thank you for making this! It will definitely be helpful for a lot of people 🙌 

I've just went through the exercises and in the number 9, I realized that there isn't any kind of description of the problem or hint on how to solve it. I guess it would probably be hard for a beginner to realize what should be done in that case.

I'd like to hear your thoughts on this.

**Comment by mattpocock** [comment]
Thanks pal!

The plan is to ship a video explaining each problem/solution, so I'll be deferring explanations to the videos!
